---
apiVersion: v1
kind: Namespace
metadata:
  name: tuxracer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuxracer
  namespace: tuxracer
spec:
  selector:
    matchLabels:
      app: tuxracer
  replicas: 1
  template:
    metadata:
      labels:
        app: tuxracer
        live.cast.ai/migrate: "true"
    spec:
      containers:
      - name: tuxracer
        image: docker.io/kisahm/tuxracer-web
        env: 
          - name: RESOLUTION
            value: "800x600"
          - name: PASSWORD
            value: "live"
          - name: VERBOSE
            value: "0"
        ports: 
          - containerPort: 80
            name: http
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      nodeSelector:
        scheduling.cast.ai/node-template: "live"
      tolerations:
        - key: "scheduling.cast.ai/node-template"
          value: "live"
          operator: "Equal"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tuxracer
  name: tuxracer
  namespace: tuxracer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: tuxracer

